### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by valaphee** [reduf/Headquarter#22]
Heya I was wondering for which version of the game this tool is?

Because it seems pretty outdated, but already got the new DH Params, and created a new patcher for it (using probabilities), new packet handler (supports Lz4, and multi/split-packets), and got the packets extracted by modding the game, which hooks into the registration functions before the initialization.

**Comment by reduf** [comment]
Hey, the project itself was written several years ago (before the git repo), but I know it's still working and is still used.

I believe the main issue is that whenever there is a game update, the key need to be updated, but that should be as simple as running the following command once a process of `Ge.exe` is started:
```
> python tools\dump_key.py
```

For the packet, it usually update without issue, though I always dump the new structure, `python tools\packet.py` and diff them with the existing one to try to detect what moved or changed if anything. In some cases that means, I need to adapt the `code/client/opcodes.h` definition. They use to often re-order stuff, so there is an helper script at `tools/update_opcode.py`, but it mostly to batch update when everything was offset by a certain number.

**Comment by reduf** [comment]
> new packet handler (supports Lz4, and multi/split-packets)

Do you mean support for the FileSrv protocol? I'm not sure what you mean by `Lz4` and `multi/split-packets`, but that can potentially be useful.

In general, this custom client saw very little developer usage and almost only by me, so there is missing a ton of stuff.

**Comment by 3vcloud** [comment]
I use this project all the time, and it's used for the kamadan bot. I've branches it though, and keep the version bumped up when I can but that's pretty much the only change I've made.

The one thing we're missing is automated checking of gw.exe via the file server to automatically keep the public key updated. These days the only reason the client version changes is to keep it in sync with the server version, so packet header changes are rare

**Comment by valaphee** [comment]
Ah this project is for Guild Wars and not Guild Wars 2?
That's why nothing matched up. ^^'

Nah Guild Wars 2 is using lz4 compression, and multiple packets are sent in one tcp packet or span multiple packets. But interesting that the encryption is nearly identical, except the hashing method.

**Comment by reduf** [comment]
> Ah this project is for Guild Wars and not Guild Wars 2?

Indeed!

> Nah Guild Wars 2 is using lz4 compression, and multiple packets are sent in one tcp packet or span multiple packets. But interesting that the encryption is nearly identical, except the hashing method.

Interesting that they use compression, I really don't know much about Gw2 except that it shares a lot in common with Gw. What might interest you is `client/portal`, I believe Gw2 uses it as well.

> ... multiple packets are sent in one tcp packet or span multiple packets

That would be just the same with Gw, shouldn't be too hard to find that out looking at `code/client/network.c`.

**Comment by valaphee** [comment]
Ah thanks, I'll take a look ^^
I already ported most things to Rust for Gw2, https://github.com/valaphee/guilded/tree/main/src/bin

But then this issue can be closed.

**Comment by reduf** [comment]
Very nice! I'll have a look :)
